kind: Namespace
apiVersion: v1
metadata:
  name: dex
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  interval: 5m
  chart:
    spec:
      chart: dex
      version: '0.8.2'
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
  values:
    config:
      # See https://dexidp.io/docs/storage/ for more options
      storage:
        type: memory
      issuer: {{ printf "https://%s.%s" .Values.subdomains.dex .Values.domain }}
      connectors:     
      {{- range .Values.idpConnectors }}
        - {{ . | toYaml | indent 10 | trim -}}
      {{- end }}
      staticClients:
        - id: k8s
          secret: {{ derivePassword 1 "maximum" .Values.secretSeed "k8s-client" .Values.domain | b64enc | quote }}
          name: "Kubernetes"
          redirectURIs: # See https://github.com/int128/kubelogin/blob/master/docs/setup.md#dex-with-github
            - http://localhost:8000
            - http://localhost:18000
            - {{ printf "https://%s.%s/oauth2/callback" .Values.subdomains.weave_gitops .Values.domain }}
          trustedPeers: # See https://dexidp.io/docs/custom-scopes-claims-clients/#cross-client-trust-and-authorized-party
            - oauth2_proxy
        - id: oauth2_proxy
          secret: {{ derivePassword 1 "maximum" .Values.secretSeed "oauth2_proxy-client" .Values.domain | b64enc | quote }}
          name: "OAuth2 Proxy"
          redirectURIs:
            - {{ printf "https://%s.%s/oauth2/callback" .Values.subdomains.oauth2_proxy .Values.domain }}
        - id: authentik
          secret: {{ derivePassword 1 "maximum" .Values.secretSeed "authentik-client" .Values.domain | b64enc | quote }}
          name: "Authentik"
          redirectURIs:
            - {{ printf "https://%s.%s/source/oauth/callback" .Values.subdomains.authentik .Values.domain }}

    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: acme
      hosts:
        - host: {{ printf "%s.%s" .Values.subdomains.dex  .Values.domain }}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - {{ printf "%s.%s" .Values.subdomains.dex  .Values.domain }}
          secretName: dex-cert
