kind: Namespace
apiVersion: v1
metadata:
  name: external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: '6.3.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  dependsOn:
    - name: nginx-ingress
      namespace: nginx-ingress
  values:
    sources:
      - service
      - ingress
    txtOwnerId: {{ printf "%s-%s" .Values.domain (derivePassword 1 "short" .Values.secretSeed "external-dns" .Values.domain | b64enc) | quote }}
    {{- range $k, $v := .Values.external_dns }}
    {{ printf "%s:" $k | nindent 4 }}
      {{- $v | toYaml | nindent 6 }}
    {{- end }}
