apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sso-authenticated
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/sub/sso-authenticated
      sourceRef:
        kind: GitRepository
        name: k3sx
        namespace: flux-system
  dependsOn:
    - name: domain-sso
      namespace: sso-system
  values:
    hosts:
      cilium: {{ printf "%s.%s" .Values.subdomains.cilium_ui .Values.domain }}
      longhorn: {{ printf "%s.%s" .Values.subdomains.longhorn_ui .Values.domain }}
    s3_backup: {{ .Values.s3_backup | toYaml | nindent 6 }}
    sso_config:
      secret_name: sso-config
      namespace: sso-system
