apiVersion: v2

name: k3sx-main
description: A Helm Chart for deploying a pragmatic infrastructure baseline on k3s
type: application
version: "0.1.45"
appVersion: "1.0"
dependencies:
  - name: common
    version: "1.16.0"
    repository: https://charts.bitnami.com/bitnami
