apiVersion: v2

name: sso-authenticated
description: A Helm Chart for deploying a SSO-autheticated endpoints after cluster-internal SSO has been setup
type: application
version: "0.1.2"
appVersion: "1.0"
